export const POPUP_SELECT_OPTION_HEIGHT = 70;
export const POPUP_SELECT_OPTION_GAP = 8;
export const POPUP_SELECT_MAX_VISIBLE_OPTIONS = 3;

export const POPUP_SELECT_MENU_MAX_HEIGHT =
  POPUP_SELECT_OPTION_HEIGHT * POPUP_SELECT_MAX_VISIBLE_OPTIONS +
  POPUP_SELECT_OPTION_GAP * (POPUP_SELECT_MAX_VISIBLE_OPTIONS - 1);
