import type { FoodItem } from "../../store/types/mealEntry";

export const MOCK_FOOD_CATALOG: readonly FoodItem[] = [
  {
    id: "shapp:1",
    title: "Вівсянка",
    brand: "SHAPP Foods",
    source: "shapp",
    imageUrl: null,
    barcode: "4820024700010",
    servingAmount: 100,
    servingUnit: "g",
    nutrients: {
      calories: 362,
      protein: 12,
      carbs: 61,
      fat: 7,
      fiber: 8,
      sugar: 1,
      sodium: 5,
    },
    description: "Цільнозернова каша з високим вмістом клітковини — класика сніданку.",
    details: "Крупи · Без добавок · Еталон 100 г",
  },
  {
    id: "shapp:2",
    title: "Куряче філе",
    brand: "Ферма",
    source: "shapp",
    imageUrl: null,
    servingAmount: 100,
    servingUnit: "g",
    nutrients: {
      calories: 165,
      protein: 31,
      carbs: 0,
      fat: 3.6,
      fiber: 0,
      sugar: 0,
      sodium: 74,
    },
    description: "Нежирне джерело білка — ідеально для основних страв.",
    details: "М'ясо птиці · Низький жир · 31 г білка на 100 г",
  },
  {
    id: "shapp:3",
    title: "Рис варений",
    brand: "Домашній",
    source: "shapp",
    imageUrl: null,
    servingAmount: 100,
    servingUnit: "g",
    nutrients: {
      calories: 130,
      protein: 2.7,
      carbs: 28,
      fat: 0.3,
      fiber: 0.4,
      sugar: 0.1,
      sodium: 1,
    },
    description: "Легкий гарнір із повільними вуглеводами.",
    details: "Крупи · Варений · Низький жир",
  },
  {
    id: "fdc:173944",
    title: "Банан",
    brand: null,
    source: "fdc",
    imageUrl:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=200&h=200&fit=crop",
    barcode: "4011",
    servingAmount: 100,
    servingUnit: "g",
    nutrients: {
      calories: 89,
      protein: 1.1,
      carbs: 23,
      fat: 0.3,
      fiber: 2.6,
      sugar: 12,
      sodium: 1,
    },
    description: "Свіжий фрукт із природною солодкістю та калієм.",
    details: "USDA FDC · Фрукти · 12 г цукрів на 100 г",
  },
  {
    id: "shapp:5",
    title: "Грецький йогурт",
    brand: "Protein Lab",
    source: "shapp",
    imageUrl: null,
    barcode: "4823107700215",
    servingAmount: 100,
    servingUnit: "g",
    nutrients: {
      calories: 97,
      protein: 9,
      carbs: 3.9,
      fat: 5,
      fiber: 0,
      sugar: 3.6,
      sodium: 36,
    },
    description: "Густий йогурт із підвищеним вмістом білка.",
    details: "Молочні · 9 г білка · Помірний жир",
  },
  {
    id: "fdc:171287",
    title: "Яйце куряче",
    brand: null,
    source: "fdc",
    imageUrl: null,
    servingAmount: 100,
    servingUnit: "g",
    nutrients: {
      calories: 155,
      protein: 13,
      carbs: 1.1,
      fat: 11,
      fiber: 0,
      sugar: 1.1,
      sodium: 124,
    },
    description: "Універсальне джерело білка та жирів для сніданку.",
    details: "USDA FDC · Яйця · ~155 ккал на 100 г",
  },
  {
    id: "shapp:7",
    title: "Сир кисломолочний 5%",
    brand: "Молокія",
    source: "shapp",
    imageUrl: null,
    servingAmount: 100,
    servingUnit: "g",
    nutrients: {
      calories: 121,
      protein: 17,
      carbs: 3,
      fat: 5,
      fiber: 0,
      sugar: 3,
      sodium: 320,
    },
    description: "М'який сир із високим вмістом білка та кальцію.",
    details: "Молочні · 17 г білка · 5% жиру",
  },
  {
    id: "shapp:8",
    title: "Арахісова паста",
    brand: "Fit Nut",
    source: "shapp",
    imageUrl: null,
    barcode: "7622210449433",
    servingAmount: 100,
    servingUnit: "g",
    nutrients: {
      calories: 588,
      protein: 25,
      carbs: 20,
      fat: 50,
      fiber: 6,
      sugar: 9,
      sodium: 17,
    },
    description: "Насіння арахісу без доданого цукру — енергійний перекус.",
    details: "Горіхова паста · Високий жир · 25 г білка",
  },
];
